version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # Mount the project directory
      # Removed line mounting db.sqlite3 directly
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Example environment variable, adjust as needed

